---
- name: install homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  tags:
    - initialize

- name: install homebrew taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items:
    - "homebrew/services"
    - "caskroom/cask"
    - "heroku/brew"
  tags:
    - initialize

- name: install core packages
  homebrew:
    name: [
      "wget",
      "gcc",
      "openssl",
      "cmake",
      "git",
      "git-lfs",
      "moreutils",
      "findutils",
      "gnupg",
      "grep",
      "screen",
      "pigz",
      "tree",
      "heroku",
    ]
    state: present
  tags:
    - initialize

- name: Generate SSH Key
  shell: "yes y | ssh-keygen -t rsa -b 4096 -C '{{ inventory_hostname }}' -N '' -f $HOME/.ssh/id_rsa"
  args:
    warn: false
  tags:
    - initialize

- name: Pull down dotfiles
  git:
    force: yes
    accept_hostkey: yes
    repo: "https://github.com/fullrobot/dotfiles.git"
    dest: "{{ lookup('env','HOME') }}/.dotfiles"
    version: "master"
  tags:
    - initialize

- name: initialize dot files
  shell: "$HOME/.dotfiles/setup.sh"
  args:
    chdir: "{{ lookup('env','HOME') }}/.dotfiles"
  tags:
    - initialize

- name: Create directory for installed apps
  file:
    path: "{{ lookup('env','HOME') }}/Applications"
    state: directory
    mode: 0775
  tags:
    - caskapps
