---
- name: install zsh shell
  homebrew:
    name:
      [
        "zsh",
        "zsh-completions",
        "zsh-autosuggestions",
        "zsh-syntax-highlighting",
      ]
    state: present
  tags:
    - terminal

- name: install Oh My Zsh
  shell: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - terminal

- name: install helpful command line tools
  homebrew:
    name: ["direnv", "watch", "nmap", "htop", "tmux"]
    state: present
  tags:
    - terminal
