---
- name: install zsh shell
  homebrew:
    name:
      [
        "zsh",
        "zsh-completions",
        "zsh-autosuggestions",
        "zsh-syntax-highlighting",
      ]
    state: present
  tags:
    - terminal

- name: Check if Oh My Zsh is already installed
  stat:
    path: "{{ lookup('env','HOME') }}/.oh-my-zsh"
  register: z
  tags:
    - terminal

- name: install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not z.stat.exists
  tags:
    - terminal

- name: install helpful command line tools
  homebrew:
    name: ["direnv", "watch", "nmap", "htop", "tmux"]
    state: present
  tags:
    - terminal
