---
- name: install openjdk
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items:
    - "adoptopenjdk/openjdk"
  tags:
    - languages

- name: install cask adoptopenjdk
  homebrew_cask:
    name: "{{ item }}"
    state: present
    install_options: "appdir=$HOME/Applications/"
  with_items:
    - "adoptopenjdk"

- name: install erlang, scala, go, nim, and python3
  homebrew:
    name: ["erlang", "golang", "scala", "sbt", "nim", "python3"]
    state: present
  tags:
    - languages

- name: install perl packages
  homebrew:
    name: ["perl-build", "plenv"]
    state: present
  tags:
    - languages

- name: install Java packages
  homebrew:
    name: ["maven", "jenv"]
    state: present
  tags:
    - languages
